rules:
  indent:
    - 2
    - 2
    - SwitchCase: 1
    - ignoredNodes: [ "ConditionalExpression" ]
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  no-unused-vars:
    - 2
    - vars: all
      args: none
  key-spacing:
    - 2
    - beforeColon: false
      afterColon: true
  object-curly-spacing:
    - 2
    - always
  space-infix-ops:
    - 2
    - int32Hint: false
  no-var:
    - 2
  prefer-spread:
    - 2
  no-trailing-spaces:
    - 2
  block-spacing:
    - 2
    - always
  comma-spacing:
    - 2
    - before: false
      after: true
  arrow-spacing:
    - 2
    - before: true
      after: true
  strict:
    - 2
    - "never"
  react/jsx-uses-react:
    - 2
  react/jsx-uses-vars:
    - 2
  react/react-in-jsx-scope: 2
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: "module"
env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
plugins: [ "react" ]
